### ISSUE TITLE
Hi, I can't intall!

### ISSUE THREAD

**Issue by mangiaparole** [PrestaShop/ps_socialfollow#20] opened 2020-04-25 19:25 UTC
I have 1.7.5 when i try to istall tell me "ops somethid gone wrong"

I also try to un zip and rizip but nothing change.

Can you hel me!

thanks

**Comment by matks** [comment] 2021-07-27 09:26
Sorry for late answer. unfortunately there is not enough details to explore this bug. I can install it just fine.

If the issue is still there, can you please fill a bug report on https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=&template=1_bug_report.md with all details (steps to reproduce, screenshot)?

I close this issue.

**Closed by matks** 2021-07-27 09:26 UTC
